alias cd=z
alias g=git
alias ls=eza
alias ll='eza -la --no-time --no-user --no-permissions --no-filesize --group-directories-first'
alias tre='eza -T'
alias ..='cd ..'
alias cl=clear
alias cls=clear
alias mk=mkdir
alias jj='cd ~'
alias df="cd ${DFL}"
alias nvc="cd ${DFL}/config/nvim"
alias gg="cd ${DEVD}"
alias vi=nvim
alias ee=exit
alias xx='explorer.exe .'
alias fr='rm -rf'
alias fc='cp -rf'
alias fm='mv -rf'
alias bat="batcat"
alias gl=pwd
